# Generated by Django 3.0.6 on 2020-06-16 21:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('real_name', models.CharField(max_length=50, null=True)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telegram_username', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('localbitcoins_username', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='localbitcoins username')),
                ('localbitcoins_feedback_score', models.IntegerField(blank=True, null=True)),
                ('localbitcoins_trade_count', models.IntegerField(blank=True, null=True)),
                ('localbitcoins_country_code_phone_number', models.CharField(blank=True, max_length=5, null=True)),
                ('localbitcoins_last_country_code_ip', models.CharField(blank=True, max_length=5, null=True)),
                ('name_match_checked', models.BooleanField(blank=True, default=False)),
                ('id_verified', models.BooleanField(blank=True, default=False)),
                ('liveness_verified', models.BooleanField(blank=True, default=False)),
                ('address_verified', models.BooleanField(blank=True, default=False)),
                ('video_verified', models.BooleanField(blank=True, default=False)),
                ('source_of_funds_verified', models.BooleanField(blank=True, default=False)),
                ('source_of_funds_limit', models.IntegerField(blank=True, default=10001, null=True)),
                ('company_verified', models.BooleanField(blank=True, default=False)),
                ('btc_deposit_address', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('LBC', 'Localbitcoins'), ('OFF', 'Offsite')], editable=False, max_length=3)),
                ('action', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], editable=False, max_length=1)),
                ('reference', models.CharField(max_length=30, null=True, unique=True)),
                ('amount_fiat', models.FloatField(editable=False)),
                ('amount_btc', models.FloatField(editable=False)),
                ('fee_btc', models.FloatField(editable=False)),
                ('exchange_price', models.FloatField(editable=False, null=True)),
                ('client_bank_account_name', models.CharField(default=None, max_length=50, null=True)),
                ('client_bank_account_number', models.CharField(default=None, max_length=8, null=True)),
                ('client_bank_account_sort_code', models.CharField(default=None, max_length=6, null=True)),
                ('bank_account_name', models.CharField(default=None, max_length=50)),
                ('bank_account_number', models.CharField(default=None, max_length=8)),
                ('bank_account_sort_code', models.CharField(default=None, max_length=6)),
                ('localbitcoins_contact_id', models.IntegerField(editable=False, null=True, unique=True)),
                ('btc_txid', models.CharField(blank=True, editable=False, max_length=64, null=True)),
                ('btc_address', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(choices=[('i', 'Initialized'), ('r', 'Released'), ('f', 'Finalized'), ('p', 'Paid'), ('pv1', 'Pending Verification - T1'), ('pv2', 'Pending Verification - T2'), ('pv3', 'Pending Verification - T3'), ('pp', 'Pending Payment'), ('d', 'Dispute'), ('c', 'Cancelled')], default='i', max_length=3)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('pre_transaction_verification_tier', models.IntegerField(default=0, editable=False)),
                ('client', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='clients.Client')),
            ],
        ),
    ]
