# Generated by Django 3.0.6 on 2020-06-17 15:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sumsub_external_user_id',
            field=models.CharField(default=models.UUIDField(default=uuid.uuid4, editable=False, unique=True), max_length=50),
        ),
    ]
