# Generated by Django 3.0.6 on 2020-06-17 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20200617_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sumsub_sdk_access_token',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
