# Generated by Django 3.0.6 on 2020-06-18 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_sumsub_sdk_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='sumsub_sdk_access_token_expiry',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
