# Generated by Django 3.0.6 on 2020-06-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_sumsub_sdk_access_token_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='localbitcoins_real_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='sumsub_external_user_id',
            field=models.CharField(default=None, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='sumsub_sdk_access_token',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='sumsub_sdk_access_token_expiry',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('i', 'Initialized'), ('r', 'Released'), ('f', 'Finalized'), ('p', 'Paid'), ('pr', 'Pending Release'), ('pv1', 'Pending Verification - T1'), ('pv2', 'Pending Verification - T2'), ('pv3', 'Pending Verification - T3'), ('pp', 'Pending Payment'), ('d', 'Dispute'), ('c', 'Cancelled')], default='i', max_length=3),
        ),
    ]
