# Generated by Django 3.0.7 on 2020-06-25 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20200619_2010'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('localbitcoins_username', 'phone_number', 'uuid')},
        ),
        migrations.AlterField(
            model_name='client',
            name='localbitcoins_country_code_phone_number',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Phone Number Country Code'),
        ),
        migrations.AlterField(
            model_name='client',
            name='localbitcoins_feedback_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Feedback Score'),
        ),
        migrations.AlterField(
            model_name='client',
            name='localbitcoins_last_country_code_ip',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Last IP Country Code'),
        ),
        migrations.AlterField(
            model_name='client',
            name='localbitcoins_real_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Real Name'),
        ),
        migrations.AlterField(
            model_name='client',
            name='localbitcoins_trade_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Trade Count'),
        ),
        migrations.AlterField(
            model_name='client',
            name='localbitcoins_username',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Username'),
        ),
        migrations.AlterField(
            model_name='client',
            name='real_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='sumsub_external_user_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='platform',
            field=models.CharField(choices=[('LBC', 'Localbitcoins'), ('OFF', 'Offsite')], default='OFF', editable=False, max_length=3),
        ),
    ]
