# Generated by Django 3.0.6 on 2020-05-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CJ_notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('body', models.TextField()),
                ('valid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Fiat_transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientOrder', models.CharField(max_length=50)),
                ('orderReference', models.CharField(max_length=50)),
                ('timestamp', models.CharField(max_length=25)),
                ('amount', models.FloatField()),
                ('operationAmount', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=4)),
                ('status', models.CharField(max_length=50)),
                ('returned', models.BooleanField(null=True)),
                ('operStatus', models.CharField(max_length=50)),
                ('complianceStatus', models.CharField(max_length=50)),
                ('paymentMethod', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('iban', models.CharField(max_length=30, null=True)),
                ('sortCode', models.CharField(max_length=6)),
                ('accountNumber', models.CharField(max_length=8)),
                ('bankSwiftCode', models.CharField(max_length=30, null=True)),
                ('transactionType', models.CharField(max_length=15, verbose_name='In/OUT')),
            ],
        ),
    ]
