# Generated by Django 3.0.6 on 2020-05-25 03:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(editable=False, max_length=30, unique=True, verbose_name='localbitcoins username')),
                ('real_name', models.CharField(max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=50, null=True)),
                ('feedback_score', models.IntegerField()),
                ('trade_count', models.IntegerField()),
                ('country_code_phone_number', models.CharField(blank=True, max_length=5, null=True)),
                ('last_country_code_ip', models.CharField(blank=True, max_length=5, null=True)),
                ('name_match_checked', models.BooleanField(blank=True, default=False)),
                ('id_verified', models.BooleanField(blank=True, default=False)),
                ('selfie_note_verified', models.BooleanField(blank=True, default=False)),
                ('liveness_verified', models.BooleanField(blank=True, default=False)),
                ('address_verified', models.BooleanField(blank=True, default=False)),
                ('video_verified', models.BooleanField(blank=True, default=False)),
                ('source_of_funds_verified', models.BooleanField(blank=True, default=False)),
                ('source_of_funds_limit', models.IntegerField(blank=True, default=None, null=True)),
                ('company_verified', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_id', models.IntegerField(editable=False, unique=True)),
                ('action', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], editable=False, max_length=1)),
                ('amount_fiat', models.FloatField(editable=False)),
                ('amount_btc', models.FloatField(editable=False)),
                ('fee_btc', models.FloatField(editable=False)),
                ('status', models.CharField(choices=[('i', 'Initialized'), ('r', 'Released'), ('p', 'Paid'), ('pv', 'Pending Verification'), ('pp', 'Pending Payment'), ('d', 'Dispute'), ('c', 'Cancelled')], max_length=2)),
                ('reference', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('payment_completed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='localbitcoins.User')),
            ],
        ),
    ]
