# Generated by Django 3.0.6 on 2020-05-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localbitcoins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('i', 'Initialized'), ('r', 'Released'), ('f', 'Finalized'), ('p', 'Paid'), ('pv', 'Pending Verification'), ('pp', 'Pending Payment'), ('d', 'Dispute'), ('c', 'Cancelled')], default='i', max_length=2),
        ),
    ]
