# Generated by Django 3.0.6 on 2020-05-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localbitcoins', '0002_auto_20200525_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='source_of_funds_limit',
            field=models.IntegerField(blank=True, default=10000, null=True),
        ),
    ]
