# Generated by Django 3.0.6 on 2020-05-29 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localbitcoins', '0004_auto_20200527_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='real_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
