# Generated by Django 3.0.6 on 2020-05-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localbitcoins', '0006_auto_20200529_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('i', 'Initialized'), ('r', 'Released'), ('f', 'Finalized'), ('p', 'Paid'), ('pv', 'Pending Verification'), ('pv2', 'Pending 2nd Verification'), ('pv3', 'Pending 3rd Verification'), ('pp', 'Pending Payment'), ('d', 'Dispute'), ('c', 'Cancelled')], default='i', max_length=3),
        ),
    ]
