# Generated by Django 3.0.6 on 2020-06-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localbitcoins', '0009_transaction_exchange_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='selfie_note_verified',
        ),
    ]
