# Generated by Django 3.0.6 on 2020-06-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('localbitcoins', '0010_remove_user_selfie_note_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pre_transaction_verification_tier',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
