# Generated by Django 3.0.6 on 2020-05-25 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('localbitcoins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_street', models.CharField(blank=True, max_length=100, null=True)),
                ('street', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('town', models.CharField(max_length=50)),
                ('postCode', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='RawSumSubNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.TextField()),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=1)),
                ('place_of_birth', models.CharField(blank=True, max_length=100, null=True)),
                ('country_of_residence', models.CharField(blank=True, max_length=3, null=True)),
                ('nationality', models.CharField(blank=True, max_length=3, null=True)),
                ('country_of_birth', models.CharField(blank=True, max_length=3, null=True)),
                ('state_of_birth', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='verifications.Address')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='localbitcoins.User')),
            ],
        ),
        migrations.CreateModel(
            name='IdDoc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=3)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('valid_until', models.DateField()),
                ('number', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField()),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='localbitcoins.User')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.CharField(max_length=50, null=True, unique=True)),
                ('inspection_id', models.CharField(blank=True, max_length=50, null=True)),
                ('correlation_id', models.CharField(blank=True, max_length=50, null=True)),
                ('review_status', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('review_answer', models.CharField(blank=True, max_length=10, null=True)),
                ('review_reject_type', models.CharField(blank=True, max_length=10, null=True)),
                ('moderation_comment', models.TextField(blank=True, null=True)),
                ('client_comment', models.TextField(blank=True, null=True)),
                ('reject_labels', models.TextField(blank=True, null=True)),
                ('access_token_for_sdk', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='localbitcoins.User')),
            ],
        ),
        migrations.CreateModel(
            name='AddressDoc',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='verifications.Address')),
                ('doc_type', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='localbitcoins.User')),
            ],
            bases=('verifications.address',),
        ),
    ]
