# Generated by Django 3.0.6 on 2020-06-02 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iddoc',
            name='issue_date',
            field=models.DateField(null=True),
        ),
    ]
