# Generated by Django 3.0.6 on 2020-06-04 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localbitcoins', '0010_remove_user_selfie_note_verified'),
        ('verifications', '0002_auto_20200602_1759'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(max_length=50)),
                ('issue_date', models.DateField()),
                ('sub_street', models.CharField(blank=True, default='hi', max_length=100, null=True)),
                ('street', models.CharField(default='hi', max_length=100)),
                ('state', models.CharField(blank=True, default='hi', max_length=50, null=True)),
                ('town', models.CharField(default='hi', max_length=50)),
                ('postCode', models.CharField(default='hi', max_length=30)),
                ('country', models.CharField(default='hi', max_length=3)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='localbitcoins.User')),
            ],
        ),
        migrations.DeleteModel(
            name='AddressDoc',
        ),
    ]
