# Generated by Django 3.0.6 on 2020-06-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('localbitcoins', '0010_remove_user_selfie_note_verified'),
        ('verifications', '0003_auto_20200604_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddressDocument',
            new_name='AddressDoc',
        ),
    ]
