# Generated by Django 3.0.6 on 2020-06-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0004_auto_20200604_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressdoc',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
