# Generated by Django 3.0.6 on 2020-06-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0007_auto_20200610_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptoaddressanalysis',
            name='address',
            field=models.CharField(editable=False, max_length=45),
        ),
    ]
