# Generated by Django 3.0.6 on 2020-06-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verifications', '0009_auto_20200610_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iddoc',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
