# Generated by Django 3.0.6 on 2020-06-17 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('localbitcoins', '0011_transaction_pre_transaction_verification_tier'),
        ('clients', '0001_initial'),
        ('verifications', '0012_auto_20200617_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressdoc',
            name='client',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='addressdoc',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localbitcoins.User'),
        ),
        migrations.AlterField(
            model_name='application',
            name='user',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localbitcoins.User'),
        ),
        migrations.AlterField(
            model_name='iddoc',
            name='client',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='clients.Client'),
        ),
        migrations.AlterField(
            model_name='iddoc',
            name='user',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localbitcoins.User'),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='localbitcoins.User'),
        ),
    ]
